sonar.organization=ashishdora

sonar.projectKey=AshishDora_devSecOps

# Point to your source code; use '.' for the root directory
sonar.sources=.

# Exclude unnecessary folders to keep the scan fast
sonar.exclusions=**/node_modules/**, **/dist/**
