name: Semgrep
on:
  workflow_dispatch: {} # Manual trigger button
  pull_request: {}      # Scans on every PR
  push:
    branches: ["main", "master"] # Scans on every push to your main branches

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep # Official scan engine
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci # Automatically uses your AppSec Platform policies
